apiVersion: apps/v1

kind: Deployment

metadata:
    name: jobhunter
    labels:
        app: jobhunter

spec:
    selector:
        matchLabels:
            app: jobhunter
    replicas: 1

    template:
        metadata:
            labels:
                app: jobhunter

        spec:
            containers:
                - name: jobhunter

                  image: icr.io/job_demo/jobapp
                  imagePullPolicy: Always

                  ports:
                      - containerPort: 5000
                  env:
                      - name: DISABLE_WEB_APP
                        value: "false"